---
- name: Configration tasks
  become: true
  tags:
    - sysctl_config
    - sysctl
  block:
    - name: Debug include
      when: sysctl_debug is defined and sysctl_debug
      ansible.builtin.include_tasks: debug/config.yml

    - name: Manage main sysctl config
      when: sysctl_config_options is defined and sysctl_config_options
      ansible.posix.sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value.value | default(item.value) }}"
        sysctl_file: "{{ item.value.file | default(sysctl_config_file | default(omit)) }}"
        state: "{{ item.value.state | default('absent') }}"
        reload: "{{ sysctl_config_reload | default(true) }}"
        sysctl_set: "{{ sysctl_config_persistent | default(true) }}"
      with_dict: "{{ sysctl_config_options }}"
